DROP FUNCTION IF EXISTS [G10_2].[udf_GetDepartment];
GO
-- =============================================
-- Author:		Heesun Arthur
-- Create date: Monday, December 7, 2020
-- Description:	Get the information on Department(Their associated code in the Major inventory list) and return it
-- =============================================
CREATE FUNCTION [G10_2].[udf_GetDepartment]()
RETURNS TABLE
AS
RETURN
	WITH Dept AS (
		SELECT DISTINCT SUBSTRING([Course (hr, crd)], 1, CHARINDEX(' ', [Course (hr, crd)])) AS DeptCode
		FROM groupnUploadfile.CoursesFall2020
	)
	SELECT DeptCode
		,CASE
			WHEN DeptCode = 'ACCT' THEN 'ACCOUNTING'
			WHEN DeptCode = 'AFST' THEN 'AFRICANA STUDIES'
			WHEN DeptCode = 'AMST' THEN 'AMERICAN STUDIES'
			WHEN DeptCode = 'ANTH' THEN 'ANTHROPOLOGY'
			WHEN DeptCode = 'ARAB' THEN 'ARABIC'
			WHEN DeptCode = 'ARTH' THEN 'ART HISTORY'
			WHEN DeptCode = 'ARTS' THEN 'ART'
			WHEN DeptCode = 'ASTR' THEN 'ASTRONOMY'
			WHEN DeptCode = 'BALA' THEN 'BUSINESS AND LIBERAL ARTS'
			WHEN DeptCode = 'BIOCH' THEN 'BIOCHEMISTRY'
			WHEN DeptCode = 'BIOL' THEN 'BIOLOGY'
			WHEN DeptCode = 'BUS' THEN 'BUSINESS'
			WHEN DeptCode = 'CERT' THEN 'CERTIFIED FULL TIME'
			WHEN DeptCode = 'CESL' THEN 'COLLEGE ENGLISH AS SECOND LANGUAGE'
			WHEN DeptCode = 'CHEM' THEN 'CHEMISTRY'
			WHEN DeptCode = 'CHIN' THEN 'CHINESE'
			WHEN DeptCode = 'CLAS' THEN 'CLASSICAL STUDIES'
			WHEN DeptCode = 'CMAL' THEN 'CLASSICAL,MIDDLE EASTERN,ASIAN LANGUAGE'
			WHEN DeptCode = 'CMLIT' THEN 'COPARATIVE LITERATURE'
			WHEN DeptCode = 'CO-OP' THEN 'COOPERATIVE EDUCATION'
			WHEN DeptCode = 'CSCI' THEN 'COMPUTER SCIENCE'
			WHEN DeptCode = 'CUNBA' THEN 'CUNY BA'
			WHEN DeptCode = 'DANCE' THEN 'DANCE'
			WHEN DeptCode = 'DRAM' THEN 'DRAMA'
			WHEN DeptCode = 'EAST' THEN 'EAST ASIAN STUDIES'
			WHEN DeptCode = 'ECON' THEN 'ECONOMICS'
			WHEN DeptCode = 'ECP' THEN 'EDUCATIONAL AND COMMUNITY PROGRAMS'
			WHEN DeptCode = 'ECPCE' THEN 'MENTAL HEALTH COUNSELING'
			WHEN DeptCode = 'ECPEL' THEN 'EDUCATIONAL LEADERSHIP'
			WHEN DeptCode = 'ECPSE' THEN 'SPECIAL EDUCATION'
			WHEN DeptCode = 'ECPSP' THEN 'SCHOOL PSYCHOLOGY'
			WHEN DeptCode = 'EECE' THEN 'ELEMENTARY AND EARLY CHILDHOOD EDUCATION'
			WHEN DeptCode = 'ENGL' THEN 'ENLGISH'
			WHEN DeptCode = 'ENSCI' THEN 'ENVIRONMENTAL SCIENCE'
			WHEN DeptCode = 'EURO' THEN 'EUROPEAN STUDIES'
			WHEN DeptCode = 'FNES' THEN 'FMAILY, NUTRITION, EXERCISE'
			WHEN DeptCode = 'FREN' THEN 'FRENCH'
			WHEN DeptCode = 'GEOL' THEN 'GEOLOGY'
			WHEN DeptCode = 'GERM' THEN 'GERMANY'
			WHEN DeptCode = 'GREEK' THEN 'GREEK'
			WHEN DeptCode = 'GRKMD' THEN 'MODERN GREEK'
			WHEN DeptCode = 'GRKST' THEN 'MODERN GREEK STUDIES'
			WHEN DeptCode = 'HEBRW' THEN 'HEBREW'
			WHEN DeptCode = 'HIST' THEN 'HISTORY'
			WHEN DeptCode = 'HMNS' THEN 'HONORS IN MATH AND SCIENCE'
			WHEN DeptCode = 'HNRS' THEN 'MACAULAY HONORS'
			WHEN DeptCode = 'HSS' THEN 'HONORS IN SOCIAL SCIENCES'
			WHEN DeptCode = 'HTH' THEN 'HUMANNITIES'
			WHEN DeptCode = 'IRST' THEN 'IRISH STUDIES'
			WHEN DeptCode = 'ITAL' THEN 'ITALIAN'
			WHEN DeptCode = 'JAZZ' THEN 'JAZZ STUDIES'
			WHEN DeptCode = 'JEWST' THEN 'JEWISH STUDIES'
			WHEN DeptCode = 'JOURN' THEN 'JOURNALISM'
			WHEN DeptCode = 'JPNS' THEN 'JAPANESE'
			WHEN DeptCode = 'KOR' THEN 'KOREAN'
			WHEN DeptCode = 'LABST' THEN 'LABOR STUDIES'
			WHEN DeptCode = 'LATIN' THEN 'LATIN'
			WHEN DeptCode = 'LBLST' THEN 'WESTERN VALUES'
			WHEN DeptCode = 'LBSCI' THEN 'LIBRARY AND INFORMATION SCIENCE'
			WHEN DeptCode = 'LCD' THEN 'LINGUISTICS AND COMMUNICATION DISORDER'
			WHEN DeptCode = 'LIBR' THEN 'LIBRARY RESEARCH'
			WHEN DeptCode = 'MAM' THEN 'MAINTAIN MATRICULATION'
			WHEN DeptCode = 'MATH' THEN 'MATHEMATICS'
			WHEN DeptCode = 'MEDST' THEN 'MEDIA STUDIES'
			WHEN DeptCode = 'MES' THEN 'MIDDLES EASTERN STUDIES'
			WHEN DeptCode = 'MUSIC' THEN 'MUSIC'
			WHEN DeptCode = 'PERM' THEN 'PERMIT'
			WHEN DeptCode = 'PHIL' THEN 'PHILOSOPHY'
			WHEN DeptCode = 'PHYS' THEN 'PHYSICS'
			WHEN DeptCode = 'PORT' THEN 'PORTGUESE'
			WHEN DeptCode = 'PSCI' THEN 'POLITICAL SCIENCE'
			WHEN DeptCode = 'PSYCH' THEN 'PSYCHOLOGY'
			WHEN DeptCode = 'RLGST' THEN 'RELIGIOUS STUDIES'
			WHEN DeptCode = 'RM' THEN 'RISK MEASUREMENT'
			WHEN DeptCode = 'RUSS' THEN 'RUSSIAN'
			WHEN DeptCode = 'SEEK' THEN 'SEEK'
			WHEN DeptCode = 'SEYS' THEN 'SECONDARY EDUCATION AND YOUTH SERVICES'
			WHEN DeptCode = 'SEYSL' THEN 'SECONDARY EDUCATION'
			WHEN DeptCode = 'SOC' THEN 'SOCIOLOGY'
			WHEN DeptCode = 'SPAN' THEN 'SPANISH'
			WHEN DeptCode = 'SPST' THEN 'SPECIAL STUDIES'
			WHEN DeptCode = 'STABD' THEN 'STUDY ABROAD'
			WHEN DeptCode = 'STPER' THEN 'STUDENT PERSONNEL'
			WHEN DeptCode = 'URBST' THEN 'URBAN STUDIES'
			WHEN DeptCode = 'WGS' THEN 'WOMEN AND GENDER STUDIES'

			END AS DepartmentName
	FROM Dept
	WHERE LEN(DeptCode) > 1